name: Build and upload to PyPI

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 300
    env:
      CIBW_SKIP: "cp27-* cp34-* pp27-* cp36-musllinux_aarch64 pp37-manylinux_aarch64 cp36-manylinux_aarch64"
      CIBW_BEFORE_BUILD: "pip install cython"
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        arch: [auto]
        include:
        - os: ubuntu-20.04
          arch: aarch64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==v2.2.2 cython

      - name: Build wheels
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_ARCHS_LINUX: ${{matrix.arch}}
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: 1

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      CIBW_SKIP: "cp27-* cp34-* pp27-*"
      CIBW_BEFORE_BUILD: "pip install cython"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Build sdist
        run: |
          pip install -U cython
          python setup.py build_ext --inplace --cython
          python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
          retention-days: 1

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
